### ISSUE TITLE
PageAction with book page counter is incredibly ugly!

### ISSUE THREAD

**Issue by janbaykara** [janbaykara/ebook-scraper#24]
<img width="25" alt="Screenshot 2022-01-31 at 01 18 47" src="https://user-images.githubusercontent.com/237556/151726699-8d3b8a68-56f7-4bc1-89b7-979ba5377f8a.png">

**Comment by obfuscatedgenerated** [comment]
For me, it at least has a transparent background, but still nothing special.

![screenshot](https://user-images.githubusercontent.com/75035364/151888450-3bdd8cf5-61f8-49f5-af8a-a3c903b80ad3.png)

**Comment by janbaykara** [comment]
I've pushed new changes (#23) that changes this up a bit. Very simple code is here:

https://github.com/janbaykara/ebook-scraper/blob/master/src/js/eventPage/actions.ts#L9-L34

**Comment by obfuscatedgenerated** [comment]
I was thinking there could be a little notification "squircle" like in UBlock, Stylus etc.

Here's a little mockup at 100x100:
![concept](https://user-images.githubusercontent.com/75035364/151957758-2357a0b9-7485-46db-9734-03252aedf155.png)

I'm not fully sure how to implement this though but I'm sure it can be done 👍

**Comment by obfuscatedgenerated** [comment]
And without the text:

![blank](https://user-images.githubusercontent.com/75035364/151958077-7595b158-b25b-4638-8fa1-689257614b5d.png)

**Comment by obfuscatedgenerated** [comment]
N.B. just slapping the text over the image in the background is not the best way to do it since if the number were to be bigger than expected, it would traverse outside the box. The "squircle" should be rendered by the code itself, this is just a proof of concept.

e.g. in the case of ubo:
![3](https://user-images.githubusercontent.com/75035364/151970301-caf19f22-f615-46e2-a0e5-54ccb1d3d984.png)

![12](https://user-images.githubusercontent.com/75035364/151970335-b4d11fc4-5a29-4929-976f-dc6ce884e8c2.png)

The box expands to fit the text.

**Comment by janbaykara** [comment]
I think that's the right approach to the counter.

Implementation is not too tricky, though I'd be tempted to lean on a canvas library like https://github.com/konvajs/konva . Might be overkill for this one little item though, I don't know.

The missing piece of the puzzle is the actual underlying extension icon — currently, we don't really have one. Open to contributions for this.

**Comment by janbaykara** [comment]
> Looking back at this, I realised I'd completely forgotten the setBadgeText method! No need for canvas methods. This should go in the background script.
> 
> Manifest v2: `chrome.browserAction.setBadgeText({text: "21"})`
> 
> Manifest v3: `chromeaction.setBadgeText({text: "21"})`

Ah this is perfect, nice one!
